shop06/account/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),

    path('registerUser/', views.RegisterUserView.as_view(), name='registerUser'),
    path('registerUserCommit/', views.registerUserCommit, name='registerUserCommit'),

    path('userInfo/', views.userInfo, name='userInfo'),
    path('updateUser/', views.UpdateUserView.as_view(), name='updateUser'),
    path('updateUserCommit/', views.updateUserCommit, name='updateUserCommit'),

    path('withdrawConfirm/', views.withdrawConfirm, name='withdrawConfirm'),
    path('withdrawCommit/', views.withdrawCommit, name='withdrawCommit'),

]

shop06/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('shopping/', include('shopping.urls')),
]

shop06/shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'shopping'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('addToCart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),

    # path('seachResult/', views.seachResult, name='seachResult'),
]

shop06/shopping/models.py
from django.db import models
from account.models import User

# Create your models here.
class Category(models.Model):
  class Meta:
        db_table = 'shopping_category'

  category_id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=256)

  def __str__(self):
        return self.name

class SearchItem(models.Model):
    pass

class Item(models.Model):
  class Meta:
        db_table = 'shopping_item'
  item_id = models.IntegerField(primary_key=True)
  name = models.CharField(max_length=128)
  manufacturer = models.CharField(max_length=32)
  color = models.CharField(max_length=16)
  price = models.IntegerField()
  stock = models.IntegerField()
  recommended = models.IntegerField()
  category = models.ForeignKey(Category, on_delete=models.CASCADE)

  def __str__(self):
        return self.name


class ItemsInCart(models.Model):
  class Meta:
        db_table = 'shopping_itemsincart'

  id = models.IntegerField(primary_key=True)
  amount = models.IntegerField()
  booked_date = models.DateTimeField()
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)


class Purchase(models.Model):
  class Meta:
        db_table = 'shopping_purchase'

  purchase_id = models.IntegerField(primary_key=True)
  destination = models.CharField(max_length=256)
  booked_date = models.DateTimeField()
  cancel = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

class PurchaseDetail(models.Model):
  class Meta:
        db_table = 'shopping_purchasedetail'

  purchase_detail_id = models.IntegerField(primary_key=True)
  amount = models.IntegerField()
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)

shop06/shopping/forms.py
from django import forms

class SearchForm(forms.Form):
    search_name = forms.CharField(max_length=100)

    def clean_search_name(self):
        search_name = self.cleaned_data['search_name']
        if search_name.strip() == '':
            raise forms.ValidationError('検索する名前を入力してください')
        return search_name

shop06/shopping/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category
from .models import Item
from .models import ItemsInCart
from django.db.models import Q
from django.utils import timezone


# Create your views here.

def index(request):
    categories = Category.objects.all()
    is_login = request.session.get('is_login', None)
    context = {
        'categories': categories,
        'is_login': is_login
    }
    return render(request, 'shopping/main.html', context)

def search(request):
    search_category = request.GET.get('search_category')
    search_name = request.GET.get('search_name', '')

    if search_category and search_category != '0':
        items = Item.objects.filter(
            Q(category__id=search_category) & 
            Q(name__icontains=search_name)
        )
    else:
        items = Item.objects.filter(name__icontains=search_name)
    
    categories = Category.objects.all()
    
    return render(request, 'shopping/searchResult.html', {
        'items': items,
        'search_name': search_name,
        'search_category': search_category,
        'categories': categories
    })

def item_detail(request, item_id):
  item = get_object_or_404(Item, item_id=item_id)
  return render(request, 'shopping/itemDetail.html', {'item': item})


def add_to_cart(request):
    if not request.session.get('is_login'):
        return redirect('account:login')
    item_id = request.POST.get('item_id')
    amount = request.POST.get('amount')

    if ItemsInCart.objects.filter(item_id=item_id).exists():
        items_in_cart = ItemsInCart.objects.get(item_id=item_id, user_id=request.session.get('user_id'))
        items_in_cart.amount += int(amount)
        items_in_cart.booked_date = timezone.now()
        items_in_cart.save()
    else:
        items_in_cart = ItemsInCart()
        items_in_cart.item = Item.objects.get(item_id=item_id)
        items_in_cart.amount = amount
        items_in_cart.booked_date = timezone.now()
        items_in_cart.user_id = request.session.get('user_id')
        items_in_cart.save()
    return redirect('shopping:cart')

def cart(request):
    cart_items = ItemsInCart.objects.all()
    return render(request, 'shopping/cart.html', {'cart_items': cart_items})

shop06/shopping/templates/shopping/cart.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>ショッピングカート内の商品一覧</h1>

    <table border="1">
      <tr>
        <th>商品名</th>
        <th>商品の色</th>
        <th>メーカー名</th>
        <th>単価</th>
        <th>数量</th>
      </tr>
      {% for cart_item in cart_items %}
      <tr>
        <td>{{ cart_item.item.name }}</td>
        <td>{{ cart_item.item.color }}</td>
        <td>{{ cart_item.item.manufacturer }}</td>
        <td>{{ cart_item.item.price }}</td>
        <td>{{ cart_item.amount }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4">カートは空です。</td>
      </tr>
      {% endfor %}
    </table>
    <a href="{% url 'shopping:index' %}">商品検索</a>へ
  </body>
</html>

shop06/shopping/templates/shopping/itemDetail.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>商品の詳細表示</h1>
    <table border="1">
      <tr>
        <th>商品名</th>
        <td>{{ item.name }}</td>
      </tr>
      <tr>
        <th>商品の色</th>
        <td>{{ item.color }}</td>
      </tr>
      <tr>
        <th>メーカー名</th>
        <td>{{ item.manufacturer }}</td>
      </tr>
      <tr>
        <th>価格</th>
        <td>{{ item.price }}</td>
      </tr>
      <tr>
        <th>在庫数</th>
        <td>{{ item.stock }}</td>
      </tr>
    </table>

    <form action="{% url 'shopping:add_to_cart' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="item_id" value="{{ item.item_id }}" />
      <br />
      数量<input type="number" name="amount" value="1" />
      <br />
      <input type="submit" value="ショッピングカートに入れる" />
    </form>

    <a href="/shopping/">商品検索</a>へ
  </body>
</html>

shop06/shopping/templates/shopping/main.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>商品の検索を行います。</h1>
    <form action="/shopping/search" method="get">
      <label for="search_category">カテゴリ:</label>
      <select name="search_category" id="search_category">
        <option value="0">すべて</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
      </select>
      <label for="search_name">キーワード</label>
      <input type="text" name="search_name" id="search_name" />
      <input type="submit" value="検索" />
    </form>

    <br />
    {% if is_login %}
    <a href="{% url 'shopping:cart' %}"> ショッピングカートを見る </a>
    {% else %}
    <a href="{% url 'account:login' %}"> ショッピングカートを見る </a>
    {% endif %}
    <br />
    <a href="#"> 購入履歴 </a>
    <br />
    {% if is_login %}
    <a href="{% url 'account:userInfo' %}"> 会員情報の確認 </a><br />
    <a href="{% url 'account:updateUser' %}"> 会員情報の変更 </a><br />
    <a href="{% url 'account:logout' %}"> ログアウト </a>
    {% else %}
    <a href="{% url 'account:login' %}"> ログイン </a>
    {% endif %}
    <br />
    <a href="#"> 管理者ページ </a>
  </body>
</html>

shop06/shopping/templates/shopping/searchResult.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>キーワードカテゴリ””の検索結果</h1>
    <p>
      カテゴリ: {% for category in categories %}
      <br />
      {% if category.category_id == search_category %}
      <br />
      {{ category.name }}{% endif %}{% endfor %}
    </p>
    <p>検索ワード: {{ search_name }}</p>
    <table border="1">
      <tr>
        <th>商品名</th>
        <th>商品の色</th>
        <th>メーカー名</th>
        <th>価格</th>
      </tr>
      {% for item in items %}
      <tr>
        <td>
          <a href="/shopping/item/{{ item.item_id }}">{{ item.name }}</a>
        </td>
        <td>{{ item.color }}</td>
        <td>{{ item.manufacturer }}</td>
        <td>{{ item.price }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4">該当する商品が見つかりませんでした。</td>
      </tr>
      {% endfor %}
    </table>

    <a href="/shopping">戻る</a>
  </body>
</html>